"""Configuration constants for the custom HTTP server."""

HOST: str = "127.0.0.1"
PORT: int = 8080
BUFFER_SIZE: int = 1024
READ_CHUNK_SIZE: int = 4096
WRITE_CHUNK_SIZE: int = 16_384
STATIC_DIR: str = "static"
SOCKET_TIMEOUT_SECS: int = 5
MAX_REQUEST_BYTES: int = 1_048_576
MAX_HEADER_BYTES: int = 16_384
MAX_BODY_BYTES: int = 524_288
MAX_TARGET_LENGTH: int = 2048
WORKER_COUNT: int = 16
REQUEST_QUEUE_SIZE: int = 1024
KEEPALIVE_TIMEOUT_SECS: int = 10
MAX_KEEPALIVE_REQUESTS: int = 1000
MAX_ACTIVE_CONNECTIONS: int = 2048
SELECT_TIMEOUT_SECS: float = 0.1
IDLE_SWEEP_INTERVAL_SECS: float = 1.0
SERVER_NAME: str = "CustomHTTPServer/2.0"
SERVER_ENGINE: str = "threadpool"
ENABLE_CHUNKED_REQUESTS: bool = True
ENABLE_CHUNKED_RESPONSES: bool = True
ENABLE_EXPECT_CONTINUE: bool = True
LOG_FORMAT: str = "plain"
DEBUG: bool = True
